import streamlit as st
import fitz  # PyMuPDF
import io
import asyncio # Import asyncio for running async functions
from agents.job_planner import plan_jobs 
from agents.deep_search_agent import RealJobSearchAgent 
from agents.tailor import tailor_application 
from agents.email_agent import send_application_email 
from agents.tracker import log_application 
from tools.pdf_utils import extract_text_from_pdf
from tools.db import create_tables, insert_application
from simple_agents import Agent, Runner

st.set_page_config(page_title="Intelligent Career Navigator", layout="centered")
st.title("Intelligent Career Navigator")

create_tables()

# Session state to store job search results and prevent re-running
if 'job_search_results' not in st.session_state:
    st.session_state.job_search_results = []
if 'resume_extracted_text' not in st.session_state:
    st.session_state.resume_extracted_text = ""
if 'planner_queries' not in st.session_state:
    st.session_state.planner_queries = []
if 'tailored_resume_content' not in st.session_state: # New session state for editable resume
    st.session_state.tailored_resume_content = ""
if 'cover_letter_content' not in st.session_state: # New session state for editable cover letter
    st.session_state.cover_letter_content = ""
if 'selected_job_for_edit' not in st.session_state: # Store selected job for editing phase
    st.session_state.selected_job_for_edit = None


st.sidebar.header("Upload Resume")
resume_file = st.sidebar.file_uploader("Choose a PDF resume", type=["pdf"])

if resume_file:
    pdf_bytes = resume_file.read()
    st.session_state.resume_extracted_text = extract_text_from_pdf(io.BytesIO(pdf_bytes))

    st.subheader("Extracted Resume Text")
    with st.expander("View text"):
        st.write(st.session_state.resume_extracted_text)

    if st.button("🔍 Run Career Navigator"):
        if st.session_state.resume_extracted_text:
            with st.spinner("Analyzing profile and planning job searches..."):
                st.session_state.planner_queries = asyncio.run(plan_jobs(st.session_state.resume_extracted_text))
            st.success("Job search plan generated!")

            # Clear previous search results and tailored content
            st.session_state.job_search_results = []
            st.session_state.tailored_resume_content = ""
            st.session_state.cover_letter_content = ""
            st.session_state.selected_job_for_edit = None


            # Perform deep search for each query
            search_agent = RealJobSearchAgent()
            st.subheader("Searching for Jobs...")
            if st.session_state.planner_queries and "searches" in st.session_state.planner_queries:
                for i, search_item in enumerate(st.session_state.planner_queries["searches"]):
                    st.write(f"--- Processing Search Query {i+1}/{len(st.session_state.planner_queries['searches'])}: '{search_item['query']}' ---")
                    st.write(f"Reason: {search_item['reason']}")
                    
                    found_jobs = asyncio.run(search_agent.search(search_item['query']))
                    
                    if found_jobs:
                        st.session_state.job_search_results.extend(found_jobs)
                        st.success(f"✅ Found {len(found_jobs)} jobs for query: '{search_item['query']}'")
                    else:
                        st.warning(f"⚠️ No jobs found for query: '{search_item['query']}'.")
            else:
                st.error("No search queries were generated by the planner.")

# Display Job Search Results
if st.session_state.job_search_results:
    st.subheader("Found Job Listings")
    st.dataframe(st.session_state.job_search_results)

    st.subheader("Generate Application Draft")
    selected_job_index = st.selectbox(
        "Select a job to generate application draft for:",
        options=range(len(st.session_state.job_search_results)),
        format_func=lambda x: f"{st.session_state.job_search_results[x]['title']} at {st.session_state.job_search_results[x]['company']}"
    )

    if st.button("Generate Draft for Editing"):
        selected_job = st.session_state.job_search_results[selected_job_index]
        st.session_state.selected_job_for_edit = selected_job # Store selected job

        # Construct a job description string for the tailor agent
        job_description_text = (
            f"Title: {selected_job.get('title', 'N/A')}\n"
            f"Company: {selected_job.get('company', 'N/A')}\n"
            f"Location: {selected_job.get('location', 'N/A')}\n"
            f"URL: {selected_job.get('url', 'N/A')}\n\n"
            "Please tailor the resume and write a cover letter for this role."
            # In a real scenario, you'd fetch the full job description from the URL
        )

        if st.session_state.resume_extracted_text:
            with st.spinner(f"Generating application draft for {selected_job['title']} at {selected_job['company']}..."):
                tailored_output = asyncio.run(tailor_application(
                    resume_text=st.session_state.resume_extracted_text,
                    job_description=job_description_text
                ))
            
            st.session_state.tailored_resume_content = tailored_output.get("tailored_resume", "No tailored resume generated.")
            st.session_state.cover_letter_content = tailored_output.get("cover_letter", "No cover letter generated.")
            st.success("Application draft generated. You can now edit and send!")
           
        else:
            st.error("Please upload a resume first to generate application drafts.")

# Display editable application content if available
if st.session_state.tailored_resume_content or st.session_state.cover_letter_content:
    st.subheader(f"✏️ Edit Application for {st.session_state.selected_job_for_edit.get('title', 'Selected Job')}")

    st.write("---")
    st.subheader("Tailored Resume (Editable)")
    st.session_state.tailored_resume_content = st.text_area(
        "Edit your tailored resume here:",
        value=st.session_state.tailored_resume_content,
        height=300,
        key="editable_resume"
    )

    st.write("---")
    st.subheader("Cover Letter (Editable)")
    st.session_state.cover_letter_content = st.text_area(
        "Edit your cover letter here:",
        value=st.session_state.cover_letter_content,
        height=300,
        key="editable_cover_letter"
    )

    st.write("---")
    if st.button("Send Application"):
        if st.session_state.selected_job_for_edit and st.session_state.resume_extracted_text:
            selected_job = st.session_state.selected_job_for_edit
            
            # Emailing the application with edited content
            with st.spinner("Sending application email..."):
                email_subject = f"Application for {selected_job['title']} at {selected_job['company']}"
                email_html_body = f"""
                <html>
                <head>
                    <style>
                        body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
                        h2 {{ color: #0056b3; border-bottom: 1px solid #eee; padding-bottom: 5px; }}
                        pre {{ background-color: #f4f4f4; padding: 15px; border-radius: 5px; overflow-x: auto; white-space: pre-wrap; word-wrap: break-word; }}
                        p {{ margin-bottom: 10px; }}
                        .job-details {{ background-color: #e6f2ff; padding: 10px; border-left: 5px solid #007bff; margin-bottom: 20px; }}
                    </style>
                </head>
                <body>
                    <div class="job-details">
                        <p><strong>Applying for:</strong> {selected_job.get('title', 'N/A')} at {selected_job.get('company', 'N/A')}</p>
                        <p><strong>Location:</strong> {selected_job.get('location', 'N/A')}</p>
                        <p><strong>Job Link:</strong> <a href="{selected_job.get('url', 'N/A')}">{selected_job.get('url', 'N/A')}</a></p>
                    </div>

                    <h2>Cover Letter</h2>
                    <p>{st.session_state.cover_letter_content.replace('\n', '<br>')}</p>

                    <h2>Tailored Resume</h2>
                    <pre>{st.session_state.tailored_resume_content}</pre>
                </body>
                </html>
                """

                email_status = asyncio.run(send_application_email(
                    subject=email_subject,
                    html_body=email_html_body
                ))
                if email_status.get("status") == "success":
                    st.success("✅ Application email sent successfully!")
                    # Clear edited content after sending
                    st.session_state.tailored_resume_content = ""
                    st.session_state.cover_letter_content = ""
                    st.session_state.selected_job_for_edit = None
                else:
                    st.error(f"❌ Failed to send application email: {email_status.get('reason')}. Check logs for details.")

            # Track the application
            log_application(
                company=selected_job['company'],
                title=selected_job['title'],
                status="Applied",
                notes=f"Applied via Career Navigator for {selected_job['url']}"
            )
            st.success("Application processed and tracked.")
        else:
            st.error("Please generate an application draft first.")

# Interview Preparation Section
st.markdown("---")
st.header("Prep for Interviews")
st.info("Get AI-powered guidance for your upcoming coding, system design, and behavioral interviews!")

prep_job_title = st.text_input("Enter the job title you want to prepare for (e.g., 'Software Engineer', 'Data Scientist', 'Security Researcher'):")

if st.button("Generate Interview Prep"):
    if prep_job_title:
        with st.spinner(f"Generating interview preparation materials for {prep_job_title}..."):
            interview_prep_agent = Agent(
                name="InterviewPrep",
                instructions="""
                You are an expert career coach and interview preparation specialist.
                Given a job title, provide concise and actionable advice for preparing for:
                1.  **Coding Rounds:** Mention common data structures, algorithms, and typical platforms.
                2.  **System Design Rounds:** Cover key concepts, common topics, and how to approach questions.
                3.  **Behavioral Rounds:** Suggest common questions, the STAR method, and how to highlight soft skills.
                
                Format your response clearly with headings for each section.
                """,
                model="gpt-4o-mini"
            )
            
            prep_advice = asyncio.run(Runner.run(interview_prep_agent, f"Generate interview prep advice for a '{prep_job_title}' role."))
            
            st.subheader(f"Interview Preparation for: {prep_job_title}")
            st.write(prep_advice)
            st.success("Interview prep generated!")
    else:
        st.warning("Please enter a job title to generate interview preparation materials.")

else:
    if not resume_file:
        st.info("Please upload your resume to begin.")